version: "3"
services:
  node-1:
    image: hyperledger/besu:22.1.0-RC5-SNAPSHOT
    container_name: "node-1"
    ports:
      - 8545:8545
      - 30303:30303
    volumes:
      - .:/usr/app/
    networks:
      qbftnetwork:
        ipv4_address: 172.23.0.2
    command: --config-file=/usr/app/node-1/config.toml

  node-2:
    image: hyperledger/besu:22.1.0-RC5-SNAPSHOT
    container_name: "node-2"
    ports:
      - 8546:8545
      - 30304:30304
    volumes:
      - .:/usr/app/
    networks:
      qbftnetwork:
        ipv4_address: 172.23.0.3
    command: --config-file=/usr/app/node-2/config.toml

  node-3:
    image: hyperledger/besu:22.1.0-RC5-SNAPSHOT
    container_name: "node-3"
    ports:
      - 8547:8545
      - 30305:30305
    volumes:
      - .:/usr/app/
    networks:
      qbftnetwork:
        ipv4_address: 172.23.0.4
    command: --config-file=/usr/app/node-3/config.toml

  node-4:
    image: hyperledger/besu:22.1.0-RC5-SNAPSHOT
    container_name: "node-4"
    ports:
      - 8548:8545
      - 30306:30306
    volumes:
      - .:/usr/app/
    networks:
      qbftnetwork:
        ipv4_address: 172.23.0.5
    command: --config-file=/usr/app/node-4/config.toml

  node-5:
    image: hyperledger/besu:22.1.0-RC5-SNAPSHOT
    container_name: "node-4"
    ports:
      - 8549:8545
      - 30307:30307
    volumes:
      - .:/usr/app/
    networks:
      qbftnetwork:
        ipv4_address: 172.23.0.6
    command: --config-file=/usr/app/node-4/config.toml

  node-6:
    image: hyperledger/besu:22.1.0-RC5-SNAPSHOT
    container_name: "node-4"
    ports:
      - 8550:8545
      - 30308:30308
    volumes:
      - .:/usr/app/
    networks:
      qbftnetwork:
        ipv4_address: 172.23.0.7
    command: --config-file=/usr/app/node-4/config.toml

  node-7:
    image: hyperledger/besu:22.1.0-RC5-SNAPSHOT
    container_name: "node-4"
    ports:
      - 8551:8545
      - 30309:30309
    volumes:
      - .:/usr/app/
    networks:
      qbftnetwork:
        ipv4_address: 172.23.0.8
    command: --config-file=/usr/app/node-4/config.toml

volumes:
  .:
networks:
    qbftnetwork:
      driver: bridge
      ipam:
        config:
          - subnet: 172.23.0.0/16
            gateway: 172.23.0.1
