data-path="/usr/app/node-1/data"

rpc-http-enabled=true
rpc-http-api=["ETH", "NET", "QBFT", "DEBUG", "ADMIN", "PERM"]
rpc-http-host="0.0.0.0"

rpc-ws-enabled=true
rpc-ws-host="0.0.0.0"

discovery-enabled=false

host-allowlist=["*"]

rpc-http-cors-origins=["all"]

genesis-file="/usr/app/genesis.json"
logging=["ALL"]
revert-reason-enabled=true
min-gas-price=0